# Generated by Django 5.2.7 on 2026-06-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
