# Generated by Django 5.2.7 on 2026-04-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_imageupload_ai_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
