# Generated by Django 5.2.7 on 2026-04-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_generatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='generation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
