# Generated by Django 5.2.7 on 2026-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_generatedimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
