# Generated by Django 5.2.7 on 2026-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_imageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='generated_supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated/'),
        ),
    ]
