# Generated by Django 5.2.7 on 2026-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_generatedimage_generated_supabase_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='audio_supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
