# Generated by Django 5.2.7 on 2025-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='ai_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
